### PR TITLE
Composite design pattern implemented.

### PR DESCRIPTION
**Pull request by Nithur-M**

### CODE REVIEW

**Review by miqdadyyy — CHANGES_REQUESTED** [review]
Hi @Nithur-M 
i think you have not implement composite design pattern yet,
you just call the package without making code of it
Please fix this

**Comment by Nithur-M** [comment]
> Hi @Nithur-M
> i think you have not implement composite design pattern yet,
> you just call the package without making code of it
> Please fix this



> Hi @Nithur-M
> i think you have not implement composite design pattern yet,
> you just call the package without making code of it
> Please fix this

No, I did code it. But IntellIj is showing my files in red color. I don't know what's wrong. Thank you.

**Comment by miqdadyyy** [comment]
Can u send a screenshot of it?

**Comment by Nithur-M** [comment]
> Can u send a screenshot of it?

github
It is compiling and outputs the results. But the status highlight is red.

**Comment by miqdadyyy** [comment]
can you fix that and push it?

**Comment by Nithur-M** [comment]
> can you fix that and push it?

yeah, I fixed that. Now check it out. Thank you.

**Comment by miqdadyyy** [comment]
LGMT

**Pull request merged**
